
OBJS = ui_main.o token_functions.o

CFLAGS = -g -O3


all: token_machine


token_machine : $(OBJS)
		cc -o token_machine $(CFLAGS) $(OBJS)

$(OBJS): tokenizer.h

clean:
	rm -f *.o token_machine

run:token_machine
	./token_machine
